apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-fe
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/truongcongtu318/tutruong-aws-accelerator-p2.git
    targetRevision: main
    path: cloud/w9/lab/gitops/k8s/web-fe
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
