apiVersion: v1
kind: ConfigMap
metadata:
  name: web-fe-config
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        location /api/ {
          proxy_pass http://web-be:8080/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
