apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-fe
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-fe
  template:
    metadata:
      labels:
        app: web-fe
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
      volumes:
      - name: nginx-config
        configMap:
          name: web-fe-config
      - name: html
        configMap:
          name: web-fe-html
