apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-be
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-be
  template:
    metadata:
      labels:
        app: web-be
    spec:
      containers:
      - name: api
        image: hashicorp/httpbin:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: web-be-config
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
