data "aws_caller_identity" "current" {}

locals {
  name = var.project_name
  tags = merge(var.common_tags, {
    Project = var.project_name
  })
}

# ─────────────────────────────────────────────────────────────
# 1. Amazon Macie Activation
# ─────────────────────────────────────────────────────────────
# Enables Macie in the target account and region.
resource "aws_macie2_account" "macie" {
  finding_publishing_frequency = "FIFTEEN_MINUTES"
  status                       = "ENABLED"
}

# ─────────────────────────────────────────────────────────────
# 2. Amazon S3 Bucket & Objects (Target to Scan)
# ─────────────────────────────────────────────────────────────
# Random suffix to ensure unique S3 bucket name
resource "random_id" "bucket_suffix" {
  byte_length = 4
}

resource "aws_s3_bucket" "macie_target" {
  bucket        = "${local.name}-scan-target-${random_id.bucket_suffix.hex}"
  force_destroy = true

  tags = merge(local.tags, {
    Name = "${local.name}-scan-target"
  })
}

# Block all public access to the S3 bucket to follow security best practices
resource "aws_s3_bucket_public_access_block" "macie_target" {
  bucket                  = aws_s3_bucket.macie_target.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Upload sample clean file
resource "aws_s3_object" "clean_file" {
  bucket       = aws_s3_bucket.macie_target.id
  key          = "clean.txt"
  source       = "${path.module}/${var.sample_clean_file_path}"
  content_type = "text/plain"

  tags = local.tags
}

# Upload sample sensitive file
resource "aws_s3_object" "sensitive_file" {
  bucket       = aws_s3_bucket.macie_target.id
  key          = "sensitive.txt"
  source       = "${path.module}/${var.sample_sensitive_file_path}"
  content_type = "text/plain"

  tags = local.tags
}

# ─────────────────────────────────────────────────────────────
# 3. Amazon Macie Classification Job
# ─────────────────────────────────────────────────────────────
# A one-time classification job to scan the created S3 bucket.
# Macie will inspect the uploaded files for sensitive data patterns.
resource "aws_macie2_classification_job" "s3_scan" {
  name        = "${local.name}-s3-scan-job"
  description = "One-time Macie classification job to scan S3 bucket for sensitive data"
  job_type    = "ONE_TIME"

  s3_job_definition {
    bucket_definitions {
      account_id = data.aws_caller_identity.current.account_id
      buckets    = [aws_s3_bucket.macie_target.id]
    }
  }

  # Ensure Macie account is enabled and files are uploaded before running the job
  depends_on = [
    aws_macie2_account.macie,
    aws_s3_object.clean_file,
    aws_s3_object.sensitive_file
  ]
}

# ─────────────────────────────────────────────────────────────
# 4. Amazon Simple Notification Service (SNS)
# ─────────────────────────────────────────────────────────────
resource "aws_sns_topic" "macie_alerts" {
  name = "${local.name}-alerts-topic"
  tags = local.tags
}

resource "aws_sns_topic_subscription" "email" {
  topic_arn = aws_sns_topic.macie_alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

# SNS Topic Policy allowing Amazon EventBridge (events.amazonaws.com) to publish
resource "aws_sns_topic_policy" "macie_alerts_policy" {
  arn    = aws_sns_topic.macie_alerts.arn
  policy = data.aws_iam_policy_document.sns_topic_policy.json
}

data "aws_iam_policy_document" "sns_topic_policy" {
  statement {
    effect  = "Allow"
    actions = ["SNS:Publish"]

    principals {
      type        = "Service"
      identifiers = ["events.amazonaws.com"]
    }

    resources = [
      aws_sns_topic.macie_alerts.arn
    ]
  }
}

# ─────────────────────────────────────────────────────────────
# 5. Amazon EventBridge Rule & Target
# ─────────────────────────────────────────────────────────────
# Catch any finding generated by Amazon Macie.
resource "aws_cloudwatch_event_rule" "macie_finding_rule" {
  name        = "${local.name}-finding-rule"
  description = "Triggers when Amazon Macie detects sensitive data findings"

  event_pattern = jsonencode({
    source      = ["aws.macie"]
    detail-type = ["Macie Finding"]
  })

  tags = local.tags
}

# Route Macie Findings events to the SNS topic
resource "aws_cloudwatch_event_target" "sns" {
  rule      = aws_cloudwatch_event_rule.macie_finding_rule.name
  target_id = "SendToSNS"
  arn       = aws_sns_topic.macie_alerts.arn
}
