name: GitOps Manifest Lint

on:
  pull_request:
    paths:
      - 'cloud/w9/day-a/manifests/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Kubeconform
        uses: yannh/kubeconform@v0.6.3
        with:
          args: "-summary -strict cloud/w9/day-a/manifests"
