name: GitOps Manifest Lint

on:
  pull_request:
    paths:
      - 'cloud/w9/day-a/manifests/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Kubeconform
        run: |
          docker run --rm -v ${{ github.workspace }}:/work \
            ghcr.io/yannh/kubeconform:latest \
            -summary -strict /work/cloud/w9/day-a/manifests
