name: validate

on:
  pull_request:
    paths:
      - "cloud/w9/lab/gitops/k8s/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Kubernetes manifests
        uses: docker://ghcr.io/yannh/kubeconform:v0.6.7
        with:
          args: >-
            -strict
            -summary
            -ignore-missing-schemas
            cloud/w9/lab/gitops/k8s